#!/bin/bash

#check allele concordance between impute-snptest-gemma
#
#Args
#$1=impute files path
#$2=snptest files path
#$3=bimbam file path
#$4=output path
#$5=chr

if [ $# -lt 5 ]
then
        echo "missing arguments!!"
        echo "USAGE: check_allele_order_isg.sh <imputed_file_path> <snptest_file_path> <bimbam_file_path> <out_path> <chr>"
        echo "<imputed_file_path>: path to the imputed genotype file;
		the script will look for a file in that path named chr*.geno.gz .
		The file must remain gzipped."
	echo "<snptest_file_path>: path to the snptest original file generated by the gemma_additional_stats_calc_snptest.sh script.
		The script will look for a file named like 1.GFR.ALL.*.stats (not the merged!);
		there should be a file for each chromosome."
	echo "<bimbam_file_path>: path to bimbam formatted file;
		The script will look for a file in this path named chr*.geno (it must be ungzipped)"
	echo "<out_path>: output files path"
	echo "<chr>: chromosome number"
        exit 1
fi




impute_geno_path=$1
snptest_file_path=$2
bimbam_files_path=$3
out_path=$4
chr=$5

mkdir -p $out_path
#comparison between impute and snptest
#impute code allele as all_0 all_1 , snptest outputs all_A all_B.
#if no changes are made in the impute output file, the following is valid:
# all_0 = all_A
# all_1 = all_B
#
#But we need to check it to be sure
#snptest vs impute
#diff <(zcat ${impute_geno_path}/chr${chr}.geno.gz | fgrep -w -f <(cut -f 1 -d " " ~/workspace/additional_stats_new/GFR.ALL/1.GFR.ALL.${chr}.stats.merged ) | cut -f 2-5 -d " ") <(fgrep -v POS ~/workspace/additional_stats_new/GFR.ALL/1.GFR.ALL.10.stats.merged | cut -f 1,3-5 -d " ") > snptest_vs_impute.diff
diff <(zcat ${impute_geno_path}/chr${chr}.geno.gz | fgrep -w -f <(cut -f 2 -d " " $snptest_file_path ) | cut -f 2-5 -d " ") <(fgrep -v pos $snptest_file_path | cut -f 2,4-6 -d " ") > $out_path/snptest_vs_impute_chr${chr}.diff

#snptest vs bimbam
#diff <(cat chr10.geno|tr "," " " | fgrep -w -f <(cut -f 1 -d " " ~/workspace/additional_stats_new/GFR.ALL/1.GFR.ALL.10.stats.merged ) | cut -f -3 -d " ") <(fgrep -v POS ~/workspace/additional_stats_new/GFR.ALL/1.GFR.ALL.10.stats.merged | cut -f 1,4-5 -d " ") > snptest_vs_bimbam.diff
diff <(cat $bimbam_files_path/chr${chr}.geno|tr "," " " | fgrep -w -f <(cut -f 2 -d " " $snptest_file_path ) | cut -f -3 -d " ") <(fgrep -v pos $snptest_file_path | cut -f 2,5-6 -d " ") > $out_path/snptest_vs_bimbam_chr${chr}.diff
