#!/usr/local/bin/bash

#ARGS passed
#$1=chr ($1)
#$2=start ($2)
#$3=end ($3)
#$4=ref_path ($4)
#$5=geno_path ($5)
#$6=out_path ($6)
#$7=chunk_n ($7)
#$8= geno_mode ($8)
 
CHR=$1
CHUNK_START=`printf "%.0f" $2`
CHUNK_END=`printf "%.0f" $3`
CHUNK=$7
STRAND_g_FILE=$8
GENO_MODE=$9

# directories
REF_DATA_DIR=$4
GENO_DATA_DIR=$5
RESULTS_DIR=$6
mkdir -p $RESULTS_DIR 

# parameters
NE=20000
BUFFER=500
K_HAPS=10000 #bigger k_hap value seems to improve accuracy

## MODIFY THE FOLLOWING THREE LINES TO ACCOMODATE OTHER PANELS
# reference data files
GENMAP_FILE=/lustre/scratch113/teams/soranzo/users/mc14/GENOTIPI/REF_PANEL/1000G/ALL_1000G_phase1integrated_v3_impute/genetic_map_chr${CHR}_combined_b37.txt
HAPS_FILE=`ls ${REF_DATA_DIR}/${CHR}.${CHUNK}.*.hap.gz`
LEGEND_FILE=`ls ${REF_DATA_DIR}/${CHR}.${CHUNK}.*.legend.gz`
# HAPS_FILE=`ls ${REF_DATA_DIR}/chr${CHR}.${CHUNK}.*.hap.gz`
# LEGEND_FILE=`ls ${REF_DATA_DIR}/chr${CHR}.${CHUNK}.*.legend.gz`
GENO_FILE=${GENO_DATA_DIR}/CHR${CHR}/IMPUTE_INPUT/chr${CHR}.geno
#SAMPLE_FILE=${GENO_DATA_DIR}/CHR${CHR}/IMPUTE_INPUT/chr${CHR}.sample

## THESE HAPLOTYPES WOULD BE GENERATED BY THE PREVIOUS SCRIPT
## SELECT ONE FROM METHOD-A AND METHOD-B BELOW
# METHOD-A: haplotypes from IMPUTE2 phasing run
#GWAS_HAPS_FILE=${RESULTS_DIR}gwas_data_chr${CHR}.pos${CHUNK_START}-${CHUNK_END}.phasing.impute2_haps
 
# METHOD-B: haplotypes from SHAPEIT phasing run
GWAS_HAPS_FILE=${GENO_DATA_DIR}/${CHR}.phased.haps
SAMPLE_FILE=${GENO_DATA_DIR}/${CHR}.phased.sample
 
# main output file
OUTPUT_FILE=${RESULTS_DIR}/chr${CHR}.$7.geno

#check impute executable path
# /nfs/team151/software/impute_v2.3.0_x86_64_static/impute2 \
# -allow_large_regions \
# -k_hap $k_hap $k_hap \
# -m $gmap \
# -h $ref1/chr$chr.hap.gz $ref2/chr$chr.hap.gz \
# -l $ref1/chr$chr.legend.gz $ref2/chr$chr.legend.gz \
# -merge_ref_panels \
# -merge_ref_panels_output_ref chr$chr.$chunkStr \
# -int $chunk_begin $chunk_end \
# -Ne 20000 \
# -buffer 250

IMPUTE=`/nfs/team151/software/impute2.3.0.1`

if [ $# -eq 9 ]
then
#impute using genotypes, not prephased haplotypes
echo "genotypes mode!!"

if [[ $CHR =~ "X" ]]
then
echo "X chromosome analysis!!"

case $CHR in
X_nonPAR)

$IMPUTE \
-chrX \
-m $GENMAP_FILE \
-h $HAPS_FILE \
-l $LEGEND_FILE \
-g $GENO_FILE \
-strand_g $STRAND_g_FILE \
-sample_g $SAMPLE_FILE \
-fill_holes \
-int $CHUNK_START $CHUNK_END \
-Ne $NE \
-o $OUTPUT_FILE \
-o_gz \
-buffer $BUFFER \
-allow_large_regions \
-seed 367946 \
-verbose
;;
X_PAR1)

$IMPUTE \
-chrX \
-Xpar \
-m $GENMAP_FILE \
-h $HAPS_FILE \
-l $LEGEND_FILE \
-g $GENO_FILE \
-strand_g $STRAND_g_FILE \
-sample_g $SAMPLE_FILE \
-fill_holes \
-int $CHUNK_START $CHUNK_END \
-Ne $NE \
-o $OUTPUT_FILE \
-o_gz \
-buffer $BUFFER \
-allow_large_regions \
-seed 367946 \
-verbose
;;
X_PAR2)

$IMPUTE \
-chrX \
-Xpar \
-m $GENMAP_FILE \
-h $HAPS_FILE \
-l $LEGEND_FILE \
-g $GENO_FILE \
-strand_g $STRAND_g_FILE \
-sample_g $SAMPLE_FILE \
-fill_holes \
-int $CHUNK_START $CHUNK_END \
-Ne $NE \
-o $OUTPUT_FILE \
-o_gz \
-buffer $BUFFER \
-allow_large_regions \
-seed 367946 \
-verbose
;;
esac

else
echo "Autosomal anlysis!!"

#$IMPUTE \
#-m $GENMAP_FILE \
#-h $HAPS_FILE \
#-l $LEGEND_FILE \
#-g $GENO_FILE \
#-fill_holes \
#-int $CHUNK_START $CHUNK_END \
#-Ne $NE \
#-o $OUTPUT_FILE \
#-o_gz \
#-buffer $BUFFER \
#-allow_large_regions \
#-seed 567346 \
#-verbose

$IMPUTE \
-m $GENMAP_FILE \
-h $HAPS_FILE \
-l $LEGEND_FILE \
-g $GENO_FILE \
-strand_g $STRAND_g_FILE \
-fill_holes \
-int $CHUNK_START $CHUNK_END \
-Ne $NE \
-o $OUTPUT_FILE \
-o_gz \
-buffer $BUFFER \
-allow_large_regions \
-seed 367946 \
-verbose

fi
else
# impute genotypes from GWAS haplotypes
echo "prephased mode!!"

#$IMPUTE \
#-use_prephased_g \
#-m $GENMAP_FILE \
#-h $HAPS_FILE \
#-l $LEGEND_FILE \
#-known_haps_g $GWAS_HAPS_FILE \
#-fill_holes \
#-int $CHUNK_START $CHUNK_END \
#-Ne $NE \
#-o $OUTPUT_FILE \
#-o_gz \
#-buffer $BUFFER \
#-allow_large_regions \
#-seed 567346 \
#-verbose

# /nfs/team151/software/impute2.3.0.1 -use_prephased_g -m $GENMAP_FILE -h $HAPS_FILE -l $LEGEND_FILE -known_haps_g $GWAS_HAPS_FILE -strand_g $STRAND_g_FILE -fill_holes -int $CHUNK_START $CHUNK_END -Ne $NE -o $OUTPUT_FILE -o_gz -buffer $BUFFER -allow_large_regions -seed 367946 -verbose
/nfs/team151/software/impute2.3.0.1 -use_prephased_g -m $GENMAP_FILE -h $HAPS_FILE -l $LEGEND_FILE -known_haps_g $GWAS_HAPS_FILE -fill_holes -int $CHUNK_START $CHUNK_END -Ne $NE -o $OUTPUT_FILE -o_gz -buffer $BUFFER -allow_large_regions -seed 367946 -verbose

fi